---
language: python
services: docker

addons:
  apt:
    packages:
    - python3-pip

install:
  - pip install -r requirements.txt

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
