---
# tasks file for ansible-role-postgresql

- name: (Debian) Include os_family vars
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- name: (RedHat 8) Include os_family vars
  include_vars: "RedHat-8.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version >= "8"

- name: (Ubuntu) Include os_family vars
  include_vars: "Debian-LTS.yml"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version <= "18.04"

- name: (PostgreSQL) Set and sanitize facts
  set_fact:
    postgres_data_dir: >-
      {{ postgres_data_dir
      if postgres_data_dir is defined
      and postgres_data_dir is string
      and postgres_data_dir != 0
      else "/var/lib/pgsql/data" }}
    postgres_conf_dir: >-
      {{ postgres_conf_dir
      if postgres_conf_dir is defined
      and postgres_conf_dir is string
      and postgres_conf_dir != 0
      else postgres_data_dir }}
    postgres_user: >-
      {{ postgres_user
      if postgres_user is defined
      and postgres_user is string
      and postgres_user != 0
      else "postgres" }}
