---

# Check for the existence of {{ pgsql_data_dir }}/PG_VERSION
# to know if pgsql_data_dir has been initialized
- name: (RedHat) Check if database is initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: pg_init

- name: (CentOS 7) Initialize postgresql
  command: "/usr/bin/postgresql-setup initdb"
  become: true
  become_user: "{{ postgres_user }}"
  when: >-
    ansible_distribution_version is version('8.0', '<') and
    not pg_init.stat.exists

- name: (CentOS 8) Initialize postgresql
  command: >-
    /usr/bin/initdb -D /var/lib/pgsql/data
    --auth-host "{{ postgres_auth }}"
    --no-locale -E 'UTF-8'
  become: true
  become_user: "{{ postgres_user }}"
  when: >-
    ansible_distribution_version is version('8.0', '>=') and
    not pg_init.stat.exists
