---

# Check for the existence of {{ pgsql_data_dir }}/PG_VERSION
# to know if pgsql_data_dir has been initialized
- name: (PostgreSQL) Check if database is initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: pg_version

- name: (CentOS 7) Initialize postgresql
  command: "/usr/bin/postgresql-setup initdb"
  when: >-
    ansible_distribution_version is version('8.0', '<') and
    not pg_version.stat.exists

- name: (CentOS 8) Initialize postgresql
  command: "/usr/bin/initdb -D /var/lib/pgsql/data --no-locale -E 'UTF-8'"
  become: true
  become_user: "{{ postgres_user }}"
  when: >-
    ansible_distribution_version is version('8.0', '>=') and
    not pg_version.stat.exists
